  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train models to generate mlruns
        run: |
          python src/ingest.py
          python src/features.py
          python src/train.py

      - name: Build Docker image
        run: docker build -t indonesian-stock-mlops:latest .
